In [1]:
import numpy as np

In [61]:
arr = np.array([1,4,9,16])
arr

array([ 1,  4,  9, 16])

In [4]:
np.square(arr)

array([  1,  16,  81, 256])

In [5]:
arr**2

array([  1,  16,  81, 256])

In [6]:
np.sqrt(arr)

array([1., 2., 3., 4.])

In [23]:
np.exp(arr)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [24]:
np.log(arr)

array([0.        , 1.38629436, 2.19722458, 2.77258872])

In [25]:
2.71828**1.38629

3.9999788256095363

In [27]:
np.exp(np.log(arr))

array([ 1.,  4.,  9., 16.])

In [28]:
arr1 = np.array([6,8,10,12])
arr1

array([ 6,  8, 10, 12])

In [29]:
arr+arr1

array([ 7, 12, 19, 28])

In [33]:
arr2 = np.array([1,2])
arr2

array([1, 2])

In [39]:
np.sum(arr)

np.int64(30)

In [40]:
np.cumsum(arr)

array([ 1,  5, 14, 30])

In [41]:
arr

array([ 1,  4,  9, 16])

In [42]:
np.mean(arr)

np.float64(7.5)

In [43]:
arr.mean()

np.float64(7.5)

In [44]:
arr.std()

np.float64(5.678908345800274)

In [45]:
np.var(arr)

np.float64(32.25)

In [46]:
arr.var()

np.float64(32.25)

In [47]:
np.min(arr)

np.int64(1)

In [48]:
arr.min()

np.int64(1)

In [49]:
arr.max()

np.int64(16)

In [50]:
np.argmin(arr)

np.int64(0)

In [51]:
arr.argmin()

np.int64(0)

In [52]:
np.argmax(arr)

np.int64(3)

In [53]:
arr.argmax()

np.int64(3)

In [54]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
arr.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [56]:
arr.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [93]:
arr3d = np.arange(27).reshape(3,3,3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [94]:
arr3d.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [95]:
arr3d.transpose(1,0,2)

array([[[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20]],

       [[ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23]],

       [[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26]]])

In [102]:
arr3d.transpose(0,1,2)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [100]:
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [70]:
arr = np.array([1,2,3,4])

In [78]:
arr.mean()

np.float64(2.5)

In [71]:
arr-2.5

array([-1.5, -0.5,  0.5,  1.5])

In [74]:
np.square(arr-2.5).sum()/4

np.float64(1.25)

In [75]:
np.var(arr)

np.float64(1.25)

In [76]:
np.std(arr)

np.float64(1.118033988749895)

In [77]:
np.sqrt(np.var(arr))

np.float64(1.118033988749895)

In [79]:
arr

array([1, 2, 3, 4])

In [80]:
np.std(arr)

np.float64(1.118033988749895)

In [91]:
np.absolute(arr-arr.mean())

array([1.5, 0.5, 0.5, 1.5])

In [92]:
np.abs(arr-arr.mean())

array([1.5, 0.5, 0.5, 1.5])

In [103]:
arr

array([1, 2, 3, 4])

In [115]:
arr = np.array([1,2,3,4])
m = arr.mean()
n = len(arr)

var = (np.square(arr - m).sum())/n
std = np.sqrt((np.square(arr - m).sum())) / np.sqrt(n)
print("var: ", var)
print("std: ", std)
print('se: ', std/np.sqrt(n))

var:  1.25
std:  1.118033988749895
se:  0.5590169943749475


In [111]:
np.std(arr)

np.float64(1.118033988749895)

In [144]:
m + var

np.float64(3.75)

In [118]:
arr_2d = np.array([[1,2,3], [4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [127]:
arr_1d = np.array([10,20,30])

In [128]:
arr_2d + arr_1d

array([[11, 22, 33],
       [14, 25, 36]])

In [135]:
arr_2d.sum(axis=0)

array([5, 7, 9])

In [141]:
np.sum(arr_2d,0)

array([5, 7, 9])

In [164]:
price = np.array([100,102,98,105,103,99,101])

def moving_average(data, window):
    return np.convolve(data, np.ones(window)/window, mode='full')

ma_3 = moving_average(price,3)
print(ma_3)

[ 33.33333333  67.33333333 100.         101.66666667 102.
 102.33333333 101.          66.66666667  33.66666667]


In [150]:
np.ones(3)/3

array([0.33333333, 0.33333333, 0.33333333])

In [158]:
(102+98+105)/3

101.66666666666667

In [162]:
(101*1/3)

33.666666666666664

In [165]:
np.nan

nan