In [2]:
import numpy as np
import pandas as pd

In [4]:
temp = pd.Series([23.5, 25.1, 19.8, 30.2], index=['월', '화', '수', '목'], name='온도')
temp

월    23.5
화    25.1
수    19.8
목    30.2
Name: 온도, dtype: float64

In [10]:
x = np.array([1,2,3,4])

x = np.append(x, [5,6,7])

In [21]:
x= np.arange(12).reshape(2,2,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [17]:
np.vstack([x, [6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
np.hstack([x, [[10],[20]]])

array([[ 0,  1,  2, 10],
       [ 3,  4,  5, 20]])

In [22]:
x = np.arange(8).reshape(2,2,2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [23]:
x.shape

(2, 2, 2)

In [29]:
new = np.array([[9,10],[11,12]])
new

array([[ 9, 10],
       [11, 12]])

In [30]:
new.shape

(2, 2)

In [32]:
np.concat([x, [new]], axis=0)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 9, 10],
        [11, 12]]])

In [33]:
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [52]:
x.shape

(2, 2, 2)

In [54]:
new = np.array([[[10,20]], [[30,40]]])
new

array([[[10, 20]],

       [[30, 40]]])

In [55]:
new.shape

(2, 1, 2)

In [56]:
np.concat([x, new], axis=1)

array([[[ 0,  1],
        [ 2,  3],
        [10, 20]],

       [[ 4,  5],
        [ 6,  7],
        [30, 40]]])

In [57]:
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [58]:
new = np.array([[[20],[30]], [[40],[50]]])
new

array([[[20],
        [30]],

       [[40],
        [50]]])

In [59]:
new.shape

(2, 2, 1)

In [62]:
np.concat([x,new], axis=2)

array([[[ 0,  1, 20],
        [ 2,  3, 30]],

       [[ 4,  5, 40],
        [ 6,  7, 50]]])

In [65]:
new = np.array([[9,10], [11,12]])
new

array([[ 9, 10],
       [11, 12]])

In [66]:
new.shape

(2, 2)

In [69]:
new[np.newaxis, :, :]

array([[[ 9, 10],
        [11, 12]]])

In [77]:
np.expand_dims(new, 1)

array([[[ 9, 10]],

       [[11, 12]]])

In [78]:
np.expand_dims(new, 1).shape

(2, 1, 2)

In [79]:
np.expand_dims(new, 0)

array([[[ 9, 10],
        [11, 12]]])

In [81]:
np.expand_dims(new, 0).shape

(1, 2, 2)

In [97]:
new.reshape(1,1,2,2)

array([[[[ 9, 10],
         [11, 12]]]])

In [87]:
new.shape

(2, 2)

In [100]:
x.shape, new.shape

((2, 2, 2), (2, 2))

In [107]:
t = np.concat([x, new.reshape(1,2,2)], axis=0)
t

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 9, 10],
        [11, 12]]])

In [112]:
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [115]:
x = x.reshape(1,2,2,2)
x

array([[[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]]])

In [118]:
x.shape, new.shape

((1, 2, 2, 2), (2, 2))

In [129]:
np.concat([x, new.reshape(1,1,2,2)], 1)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 9, 10],
         [11, 12]]]])

In [ ]:
x_4d = np.concat([x, new.reshape(1, 1, 2, 2)], 1)
x_4d, x_4d.shape

(array([[[[ 0,  1],
          [ 2,  3]],
 
         [[ 4,  5],
          [ 6,  7]],
 
         [[ 9, 10],
          [11, 12]]]]),
 (1, 3, 2, 2))

In [ ]:
x_1d = np.array([100,200,300,400,500,600])
x_1d.shape

(6,)

In [ ]:
x_1d = x_1d.reshape(1,3,2,1)
x_1d

array([[[[100],
         [200]],

        [[300],
         [400]],

        [[500],
         [600]]]])

In [155]:
x_4d.shape, x_1d.shape

((1, 3, 2, 2), (1, 3, 2, 1))

In [175]:
x = np.concat([x_4d, x_1d], 3)
x

array([[[[  0,   1, 100],
         [  2,   3, 200]],

        [[  4,   5, 300],
         [  6,   7, 400]],

        [[  9,  10, 500],
         [ 11,  12, 600]]]])

In [176]:
x.shape

(1, 3, 2, 3)

In [182]:
new = np.arange(13,19)
new = new.reshape(1,1,2,3)
new.shape

(1, 1, 2, 3)

In [184]:
x = np.concat([x, new], 1)
x

array([[[[  0,   1, 100],
         [  2,   3, 200]],

        [[  4,   5, 300],
         [  6,   7, 400]],

        [[  9,  10, 500],
         [ 11,  12, 600]],

        [[ 13,  14,  15],
         [ 16,  17,  18]]]])

In [187]:
new = np.arange(50,62).reshape(4,3)
new, new.shape

(array([[50, 51, 52],
        [53, 54, 55],
        [56, 57, 58],
        [59, 60, 61]]),
 (4, 3))

In [189]:
x.shape

(1, 4, 2, 3)

In [192]:
new = new.reshape(1,4,1,3)
new

array([[[[50, 51, 52]],

        [[53, 54, 55]],

        [[56, 57, 58]],

        [[59, 60, 61]]]])

In [194]:
x = np.concat([x,new], 2)
x

array([[[[  0,   1, 100],
         [  2,   3, 200],
         [ 50,  51,  52]],

        [[  4,   5, 300],
         [  6,   7, 400],
         [ 53,  54,  55]],

        [[  9,  10, 500],
         [ 11,  12, 600],
         [ 56,  57,  58]],

        [[ 13,  14,  15],
         [ 16,  17,  18],
         [ 59,  60,  61]]]])

In [195]:
x.shape

(1, 4, 3, 3)

In [199]:
new =np.arange(12).reshape(1,4,3,1)
new, new.shape

(array([[[[ 0],
          [ 1],
          [ 2]],
 
         [[ 3],
          [ 4],
          [ 5]],
 
         [[ 6],
          [ 7],
          [ 8]],
 
         [[ 9],
          [10],
          [11]]]]),
 (1, 4, 3, 1))

In [203]:
new = np.arange(12).reshape(3,4)
new, new.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 (3, 4))

In [205]:
new = new.reshape(1,1,3,4)
new, new.shape

(array([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]]]]),
 (1, 1, 3, 4))

In [207]:
x = np.concat([x,new], 1)
x

array([[[[  0,   1, 100,   0],
         [  2,   3, 200,   1],
         [ 50,  51,  52,   2]],

        [[  4,   5, 300,   3],
         [  6,   7, 400,   4],
         [ 53,  54,  55,   5]],

        [[  9,  10, 500,   6],
         [ 11,  12, 600,   7],
         [ 56,  57,  58,   8]],

        [[ 13,  14,  15,   9],
         [ 16,  17,  18,  10],
         [ 59,  60,  61,  11]],

        [[  0,   1,   2,   3],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11]]]])

In [211]:
x, x.shape

(array([[[[  0,   1, 100,   0],
          [  2,   3, 200,   1],
          [ 50,  51,  52,   2]],
 
         [[  4,   5, 300,   3],
          [  6,   7, 400,   4],
          [ 53,  54,  55,   5]],
 
         [[  9,  10, 500,   6],
          [ 11,  12, 600,   7],
          [ 56,  57,  58,   8]],
 
         [[ 13,  14,  15,   9],
          [ 16,  17,  18,  10],
          [ 59,  60,  61,  11]],
 
         [[  0,   1,   2,   3],
          [  4,   5,   6,   7],
          [  8,   9,  10,  11]]]]),
 (1, 5, 3, 4))

In [214]:
new = np.zeros(5*3*4).reshape(1,5,3,4)
new, new.shape

(array([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]),
 (1, 5, 3, 4))

In [219]:
x = np.concat([x, new], 0)
x.shape

(2, 5, 3, 4)

In [222]:
x[1].shape

(5, 3, 4)

In [223]:
first = x[0]
second = x[1]
first.shape, second.shape

((5, 3, 4), (5, 3, 4))

In [233]:
np.concat([first, second],2).shape

(5, 3, 8)

In [237]:
x = x[0]
x

array([  0.,   1., 100.,   0.])

In [242]:
x = np.arange(3*3*4).reshape(3,3,4)
x, x.shape

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]],
 
        [[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]]]),
 (3, 3, 4))

In [247]:
filter = np.zeros(x.shape)
filter[1] = np.ones((3,4))
filter

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [255]:
x[filter == 1]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [264]:
x*filter

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [34]:
data_array = np.array([
    [23.5, 60, 0],
    [25.1, 65, 0],
    [19.8, 70, 5.2],
    [30.2, 55, 0]
])

In [37]:
df = pd.DataFrame(data_array, index=['월', '화', '수', '목'], columns=['온도', '습도', '강수량'])

In [38]:
df

,온도,습도,강수량
월,23.5,60.0,0.0
화,25.1,65.0,0.0
수,19.8,70.0,5.2
목,30.2,55.0,0.0


In [47]:
df.loc['화', ['강수량', '습도']]

강수량     0.0
습도     65.0
Name: 화, dtype: float64